- hosts: all
  user: root
  become: true
  tasks:
  - user: name=sita
          state=present
          uid=1203
          home=/data/sita
  - group: name=sita1
           state=present
  - copy: src=/etc/passwd
          dest=/data/sita
  - group: name=shyama
           state=present
